name: GitHub Pages

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
    types: [closed]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-github-actions
        enable_jekyll: true
